[workspace]
members = [
    "crates/zkpoker_lib",
    "crates/deck",
    "crates/deal",
    "crates/reveal",
    "crates/showdown",
    "crates/bet",
    "crates/hash_helper"
]
default-member = "crates/deck"
